name: CI/CD Pipeline

# When to run this workflow
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

# Jobs define what the workflow does
jobs:
  # Job 1: Test the code
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python test_hello.py
        
    - name: Test Flask application
      run: |
        # Test Flask app starts
        python -c "from hello import app; print('Flask app imported successfully')"

  # Job 2: Code quality checks
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install linting tools
      run: |
        pip install flake8
        
    - name: Run linting
      run: |
        flake8 hello.py test_hello.py --max-line-length=100

  # Job 3: Docker Build and Deploy
  docker-deploy:
    needs: [test, lint]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image with tags
      run: |
        docker build -t hello-cicd-flask:latest .
        docker build -t hello-cicd-flask:${{ github.sha }} .
        docker build -t hello-cicd-flask:${{ github.ref_name }} .
        
    - name: Test Docker container
      run: |
        docker run -d --name test-container -p 8080:8000 hello-cicd-flask:latest
        sleep 10
        curl -f http://localhost:8080/health || exit 1
        curl -f http://localhost:8080/ || exit 1
        docker stop test-container
        docker rm test-container
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
        
    - name: Push to GitHub Container Registry
      run: |
        docker tag hello-cicd-flask:latest ghcr.io/${{ github.repository }}:latest
        docker tag hello-cicd-flask:${{ github.sha }} ghcr.io/${{ github.repository }}:${{ github.sha }}
        docker tag hello-cicd-flask:${{ github.ref_name }} ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        
        docker push ghcr.io/${{ github.repository }}:latest
        docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}