name: CI/CD Pipeline

# When to run this workflow
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Jobs define what the workflow does
jobs:
  # Job 1: Test the code
  test:
    runs-on: ubuntu-latest  # Use GitHub's free Ubuntu runners
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Step 4: Run tests
    - name: Run tests
      run: |
        python test_hello.py
        
    # Step 5: Run the application to verify it works
    - name: Test application
      run: |
        python hello.py

  # Job 2: Code quality checks (optional but good practice)
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install linting tools
      run: |
        pip install flake8
        
    - name: Run linting
      run: |
        flake8 hello.py test_hello.py --max-line-length=100
